Traceback (most recent call last):
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/darlon/Pesquisa/env/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
seed = 42
n = 15
names.random.seed(seed)
np.random.seed(seed)
sexo = np.array(['male' if x else 'female' for x in np.random.randint(0,2,n)])
nomes = np.array([names.get_first_name(gender=g) for g in sexo])
sobrenomes = np.array([names.get_last_name() for _ in sexo])
idades = np.random.randint(10,60,n)
pesos = np.random.randint(30,120,n)
print('Sexo     :',sexo)
print('Nome     :',nomes)
print('Sobrenome:',sobrenomes)
print('Idade    :',idades)
print('Peso     :',pesos)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [2], line 4[0m
[1;32m      2[0m n [38;5;241m=[39m [38;5;241m15[39m
[1;32m      3[0m names[38;5;241m.[39mrandom[38;5;241m.[39mseed(seed)
[0;32m----> 4[0m np[38;5;241m.[39mrandom[38;5;241m.[39mseed(seed)
[1;32m      5[0m sexo [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;124m'[39m[38;5;124mmale[39m[38;5;124m'[39m [38;5;28;01mif[39;00m x [38;5;28;01melse[39;00m [38;5;124m'[39m[38;5;124mfemale[39m[38;5;124m'[39m [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m np[38;5;241m.[39mrandom[38;5;241m.[39mrandint([38;5;241m0[39m,[38;5;241m2[39m,n)])
[1;32m      6[0m nomes [38;5;241m=[39m np[38;5;241m.[39marray([names[38;5;241m.[39mget_first_name(gender[38;5;241m=[39mg) [38;5;28;01mfor[39;00m g [38;5;129;01min[39;00m sexo])

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

